baseURL = "https://newb.tokyo/"
languageCode = "ja-JP"
title = "newb.tokyo"
theme = "hugo-paper"
canonifyurls = true
publishDir = "docs"
hasCJKLanguage = true
googleAnalytics = "UA-108444633-2"
relativeUrls = true
staticDir = "docs"

[params]
author = "umasoya"

[[params.menu]]
name = "home"
path = "/"

[[params.menu]]
name = "about"
path = "/about/"
