version: '3.7'

services:

    node:
        image: node:lts-alpine
        volumes:
            - .:/newb.tokyo:rw
            - node_modules:/newb.tokyo/node_modules
        working_dir: /newb.tokyo

    hugo:
        build: ./docker/hugo
        volumes:
            - .:/newb.tokyo:rw
        working_dir: /newb.tokyo
        ports:
            - 1313:1313
            - 443:443
        logging:
            options:
                max-size: '100k'
                max-file: '3'

volumes:
    node_modules:
