version: 2.1

persist: &persist
  root: .
  paths:
    - docs

executors:
  hugo:
    docker:
      - image: umasoya/hugo

jobs:
  build:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - run:
          name: build html
          command: hugo
      - persist_to_workspace:
          <<: *persist
          # root: .
          # paths:
          #   - docs

  webpack:
    docker:
      - image: circleci/node:latest
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
          name: init
          command: npm install
      - run:
          name: build js
          command: npm run build
      - persist_to_workspace:
          <<: *persist
        # root: .
        #  paths:
        #    - docs

  push:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - run:
          name: push new docs
          command: |
            git config user.name "umasoya"
            git config user.email "basilisk.0331@icloud.com"
            git add docs
            git commit -m '[CircleCI] new docs'
            git push --force-with-lease

workflows:
  version: 2
  build-push:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - webpack:
          requires:
            - build
      - push:
          requires:
            - build
            - webpack
