version: 2.1
executors:
  hugo:
    docker:
      - image: umasoya/hugo

jobs:
  build:
    executor: hugo
    working_directory: /home/circleci/go/src/newb.tokyo
    steps:
      - checkout
      - run:
        name: build html
        command: hugo

  push:
    executor: hugo
    working_directory: /home/circleci/go/src/newb.tokyo
    steps:
      - checkout
      - run:
        name: push docs
        command: |
          git add docs
          git commit -m 'build by CircleCI'
          git push origin master

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
    filters:
      branches:
        only:
          - master
      - push:
        requires:
          - build
