version: 2.1
executors:
  hugo:
    docker:
      - image: umasoya/hugo

jobs:
  build:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - run:
          name: build html
          command: hugo

  push:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - run:
          name: push new docs
          command: |
            git add docs
            git commit -m '[CircleCI] new docs'
            git push

workflows:
  version: 2
  build-push:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - push:
          requires:
            - build
