version: 2.1

executors:
  hugo:
    docker:
      - image: umasoya/hugo
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - run:
          name: build html
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - docs

  webpack:
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: init
          command: npm ci
      - run:
          name: build js
          command: npm run build
      - run:
          name: compile sass
          command: npm run sass
      - run: git diff --name-only
      - persist_to_workspace:
          root: .
          paths:
            - docs

  push:
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: push new docs
          command: |
            git config user.name "umasoya"
            git config user.email "basilisk.0331@icloud.com"
            git add docs
            git commit -m '[ci skip] build contents by CircleCI'
            git push origin master

workflows:
  version: 2
  build-push:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - webpack:
          requires:
            - build
      - push:
          requires:
            - build
            - webpack
