version: 2.1

executors:
  hugo:
    docker:
      - image: umasoya/hugo
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - run:
          name: build html
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - docs
  npm-check-update:
      executor: default
      steps:
          - checkout
          - run:
              name: update packages
              command: ncu -e
          - run:
              name: push new docs
              command: |
                if [[ `git status --porcelain` ]]; then
                    git config user.name "umasoya"
                    git config user.email "basilisk.0331@icloud.com"
                    git add .
                    git commit -m '[ci skip] build contents by CircleCI'
                    git push origin master
                else
                    echo "No changes at packages"
                fi

  webpack:
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build and compile
          command: npm run build
      - run: git diff --name-only
      - persist_to_workspace:
          root: .
          paths:
            - docs

  push:
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: push new docs
          command: |
            if [[ `git status --porcelain` ]]; then
                git config user.name "umasoya"
                git config user.email "basilisk.0331@icloud.com"
                git add .
                git commit -m '[ci skip] build contents by CircleCI'
                git push origin master
            else
                echo "No changes at docs"
            fi

workflows:
  version: 2
  build-push:
    jobs:
      - build:
          filters:
            branches:
                only: master
      - webpack:
          filters:
            branches:
                only: master
          requires:
            - build
      - push:
          filters:
            branches:
                only: master
          requires:
            - build
            - webpack
  package-update:
      triggers:
          - schedule:
              cron: "0 0 1 */1 *"
              filters:
                  brances:
                      only:
                          - master
      jobs:
          - npm-check-update
