version: 2.1

executors:
  hugo:
    docker:
      - image: umasoya/hugo
  default:
    docker:
      - image: circleci/node:latest

jobs:
  build:
    branches:
        only:
            - master
    executor: hugo
    working_directory: /go/src/newb.tokyo
    steps:
      - checkout
      - run:
          name: build html
          command: hugo
      - persist_to_workspace:
          root: .
          paths:
            - docs

  webpack:
    branches:
        only:
            - master
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build and compile
          command: npm run build
      - run: git diff --name-only
      - persist_to_workspace:
          root: .
          paths:
            - docs

  push:
    branches:
        only:
            - master
    executor: default
    working_directory: ~/newb.tokyo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: push new docs
          command: |
            git config user.name "umasoya"
            git config user.email "basilisk.0331@icloud.com"
            git add .
            git commit -m '[ci skip] build contents by CircleCI'
            git push origin master

workflows:
  version: 2
  build-push:
    jobs:
      - build:
      - webpack:
          requires:
            - build
      - push:
          requires:
            - build
            - webpack
